# Generated by Django 2.0.10 on 2019-03-04 13:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conf',
            new_name='Conference',
        ),
    ]
