# Generated by Django 2.0.10 on 2019-03-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_auto_20190304_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='published_post_date',
        ),
    ]
